name: Build Docker Images

on: push

env:
  QBS_BRANCH: v1.20.1
  QT_MAJOR: "515"
  QT_VERSION: "5.15.2"

jobs:
  qbs-clang:
    name: "Qbs + GCC"
    strategy:
      fail-fast: false
      matrix:
        include:
          - gcc_major: 9
            distro: focal
          - gcc_major: 10
            distro: focal
          - gcc_major: 11
            distro: focal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: GCC ${{ matrix.gcc_major }} + Qbs ${{ env.QBS_BRANCH }}
        uses: docker/build-push-action@v2
        with:
          buildkitd-flags: --debug
          target: qbs-gcc
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/qbs-gcc${{ matrix.gcc_major }}:latest
            arbmind/qbs-gcc${{ matrix.gcc_major }}:qbs_${{ env.QBS_BRANCH }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            GCC_MAJOR=${{ matrix.gcc_major }}
            QT_MAJOR=${{ env.QT_MAJOR }}
            QT_VERSION=${{ env.QT_VERSION }}
            QBS_BRANCH=${{ env.QBS_BRANCH }}

      - name: GCC ${{ matrix.gcc_major }} + Qt ${{ env.QT_VERSION }} + Qbs ${{ env.QBS_BRANCH }}
        uses: docker/build-push-action@v2
        with:
          target: qbs-gcc-qt
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/qbs-gcc${{ matrix.gcc_major }}-qt${{ env.QT_MAJOR }}:latest
            arbmind/qbs-gcc${{ matrix.gcc_major }}-qt${{ env.QT_MAJOR }}:qbs_${{ env.QBS_BRANCH }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            GCC_MAJOR=${{ matrix.gcc_major }}
            QT_MAJOR=${{ env.QT_MAJOR }}
            QT_VERSION=${{ env.QT_VERSION }}
            QBS_BRANCH=${{ env.QBS_BRANCH }}
